language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t tushargoyal/react-app -f Dockerfile.dev .
script:
    - docker run tushargoyal/react-app npm run test -- --coverage